0-custom_http_response_header

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,61 +1,90 @@
 #!/usr/bin/env bash
-# Configures Nginx server so that /redirect_me redirects to another page
-# Configures /redirect_me as a "301 Moved Permanently".
-# Includes a custom 404 page containing "Ceci n'est pas une page".
-# Script to configure Nginx with a custom HTTP response header
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-apt-get update
-apt-get install -y nginx
+# uncomment to see the script run in action
+#set -x
 
-# create dorectory and file with content Hello World!
-mkdir /etc/nginx/html
-touch /etc/nginx/html/index.html
-echo "Hello World!" > /etc/nginx/html/index.html
+# colors
+blue='\e[1;34m'
+brown='\e[0;33m'
+green='\e[1;32m'
+reset='\033[0m'
 
-# Make sure Nginx is listening on port 80
-printf %s "server {
-     listen      80 default_server;
-     listen      [::]:80 default_server;
-     root        /etc/nginx/html;
-     index       index.html index.htm;
+echo -e "${blue}Updating and doing some minor checks...${reset}\n"
 
+function install() {
+	command -v "$1" &> /dev/null
+
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: ${brown}$1${reset}\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${green}${1} is already installed.${reset}\n"
+	fi
 }
-" > /etc/nginx/sites-available/default
 
-#  creates an empty file named 404.html
-touch /etc/nginx/html/404.html
-echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html
+install nginx #install nginx
 
-# Display script completion message
-echo "Nginx installation and configuration completed."
+echo -e "\n${blue}Setting up some minor stuff.${reset}\n"
 
-# Create configuration file for the redirection.
-echo "server {
-    listen      80;
-    listen      [::]:80;
-    root        /etc/nginx/html;
-    index       index.html index.htm;
+# allowing nginx on firewall
+sudo ufw allow 'Nginx HTTP'
 
-    # Add index.php to the list if you are using PHP
-    index index.html index.htm index.nginx-debian.html;
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
 
-    location /redirect_me {
-       return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
-    }
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
 
-    error_page 404 /404.html;
-    location /404 {
-	root /etc/nginx/html;
-	internal;
-    }
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
 
-}" | sudo tee /etc/nginx/sites-available/default
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
 
-# Enable the new site configuration
-sudo ln -s "server_name _;/a add_hearder X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
 
-# Test nginx configuration and reload
-sudo nginx -t
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
 
-# Restarts the Nginx service to apply the configuration changes.
-sudo service nginx reload
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
